# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='任务名称')),
                ('created_time', models.IntegerField(verbose_name='创建时间')),
                ('updated_time', models.IntegerField(verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(verbose_name='是否删除')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
